#@TYPE: Machine
#@NAME: AM62L Badge
#@DESCRIPTION: Machine configuration for the TI AM62L Badge

require conf/machine/include/am62lxx.inc

KERNEL_DEVICETREE_PREFIX = " \
    ti/k3-am62l3-badge \
"

KERNEL_DEVICETREE = ""

UBOOT_MACHINE = "am62lx_badge_defconfig"

TFA_BOARD = "am62l3-badge"
