require conf/machine/include/k3r5-falcon.inc
require conf/machine/include/am62xx-k3r5.inc

UBOOT_CONFIG_FRAGMENTS = "k3_r5_falcon.config"

TI_UPSTREAM_TOOLS_MACHINE = "am62xx-evm-k3r5"

UBOOT_CONFIG:remove:k3r5-falcon = "${UBOOT_TEST_BUILD_CONFIGS}"
