#@TYPE: Machine
#@NAME: AM62DXX EVM
#@DESCRIPTION: Machine configuration for the TI AM62DXX EVM

require conf/machine/include/am62dxx.inc

KERNEL_DEVICETREE_PREFIX = " \
    ti/k3-am62d2 \
    ti/k3-am62a7-sk \
    ti/k3-am62x-sk-csi2 \
    ti/k3-am62x-sk-ecap-capture \
    ti/k3-am62x-sk-eqep \
    ti/k3-am62x-sk-hdmi \
    ti/k3-am62x-sk-lpm \
    ti/k3-am62x-sk-mcspi-loopback \
    ti/k3-am62x-sk-pwm \
"

KERNEL_DEVICETREE = ""

FIT_CONF_DEFAULT_DTB = "k3-am62d2-evm.dtb"

UBOOT_MACHINE = "am62dx_evm_a53_defconfig"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "ti-adc-fw"
