include dsplib.inc

MATHLIB_INSTALL_DIR = "${MATHLIB_C66_INSTALL_DIR}/packages"
DSPLIB_INSTALL_DIR_RECIPE = "${DSPLIB_C66_INSTALL_DIR_RECIPE}"
DSPLIB_INSTALL_DIR = "${DSPLIB_C66_INSTALL_DIR}"
DSPLIB_BUILD_TARGET = "c66x"

DEPENDS += "mathlib-c66x"
