include dsplib.inc

MATHLIB_INSTALL_DIR = "${MATHLIB_C674_INSTALL_DIR}/packages"
DSPLIB_INSTALL_DIR_RECIPE = "${DSPLIB_C674_INSTALL_DIR_RECIPE}"
DSPLIB_INSTALL_DIR = "${DSPLIB_C674_INSTALL_DIR}"
DSPLIB_BUILD_TARGET = "c674x"

DEPENDS += "mathlib-c674x"
