# PipeWire sink configuration for AM62D.

context.objects = [
    {
        factory = adapter
        args = {
            factory.name           = api.alsa.pcm.sink
            node.name              = "alsa_audio_sink"
            node.description       = "Audio Output"
            media.class            = "Audio/Sink"
            api.alsa.path          = "hw:AM62D2EVM,0"
            audio.rate             = 48000
            audio.channels         = 8
            audio.position         = [ FL FR FC LFE RL RR SL SR ]
        }
    }
]
