# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ti-test"
BBFILE_PATTERN_meta-ti-test := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ti-test = "10"

LAYERSERIES_COMPAT_meta-ti-test = "whinlatter wrynose"

# Set a variable to get to the top of the metadata location
TITESTBASE := '${@os.path.normpath("${LAYERDIR}/")}'

LICENSE_PATH += "${LAYERDIR}/licenses"

LAYERDEPENDS_meta-ti-test = " \
    core \
    openembedded-layer \
    networking-layer \
    filesystems-layer \
    meta-python \
"

BBFILES_DYNAMIC += " \
"

# Codecs in ffmpeg with questionable patent status are not included by
# default.  As this entire layer is purely optional for testing purposes only
# and not meant to be shipped, add support for the ffmpeg commercial license.
LICENSE_FLAGS_ACCEPTED:append:ti-soc = " commercial_ffmpeg"
