include dsplib.inc

MATHLIB_INSTALL_DIR = "${MATHLIB_C64P_INSTALL_DIR}/packages"
DSPLIB_INSTALL_DIR_RECIPE = "${DSPLIB_C64P_INSTALL_DIR_RECIPE}"
DSPLIB_INSTALL_DIR = "${DSPLIB_C64P_INSTALL_DIR}"
DSPLIB_BUILD_TARGET = "c64Px"
